services:
  mysql:
    image: mysql:8.0.25
    platform: linux/x86_64
    container_name: ${APP_NAME}-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF-8
    ports:
      - ${DB_PORT}:3306

  redis:
    image: 'redis:6-alpine'
    platform: linux/x86_64
    container_name: ${APP_NAME}-redis
    ports:
      - ${REDIS_PORT}:6379
